Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      PackageType: Image
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile
